name: Feature Request
description: Request a new feature for Homework Companion
labels: [Request]
body:
- type: markdown
  attributes:
    value: "# Homework Companion Feature Request Form"
- type: dropdown
  attributes:
    label: Version
    description: What version of Homework Companion are you using?
    options: [Stable, Development]
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Describe the feature you'd like to see implemented. Is your feature request related to a problem?
  validations:
    required: true
- type: textarea
  attributes:
    label: References (optional)
    description: If applicable, add screenshots or videos to help explain your request here.
  validations:
    required: false
- type: markdown
  attributes:
    label: Additional info (optional)
    description: Add any other context about the feature request here.
  validations:
    required: false
- type: input
  attributes:
    label: Discord username (optional)
    description: You may optionally provide your Discord username, so that we may contact you directly about the issue.
    placeholder: ex. username#1234
  validations:
    required: false